# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'TRUBA Kullanıcı Dokümanları'
copyright = '2021, TÜBİTAK ULAKBİM'
author = 'TÜBİTAK ULAKBİM'
html_title = "TRUBA Kullanıcı Dokümanları"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_togglebutton',
    'sphinx_copybutton',
    'sphinx_design',
    'sphinx_tabs.tabs',
    'sphinx_last_updated_by_git'
    
    
]

html_css_files = ['custom.css']


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'tr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'sphinx_rtd_theme'
html_theme = 'sphinx_book_theme'
#html_theme = 'furo'
#html_theme = 'pydata_sphinx_theme'
#html_theme = "sphinx_material"
#html_theme = 'karma_sphinx_theme'


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".


html_logo = '_static/TRUBA_doc-footer.png'

html_static_path = ['_static']

html_theme_options = {
    "show_toc_level": 2,
    "body_max_width": "1200px",  # Tüm sayfaya yayılmasını sağlar
    "footer": "_templates/layout.html",
    "show_navbar_prev_next": True,
    "home_page_in_toc" : True,
    "max_navbar_depth" : 2
}

def setup(app):
    app.add_css_file('site_theme.css')

html_show_sourcelink = False


